
spring:
  application:
    name: shortCode

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/short_code
    username: postgres
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3s

short-code:
  route:
    schema-count: 16
    table-count-per-schema: 64
    schema-prefix: code_
    table-prefix: short_url_mapping_
  cache:
    local-expire-minutes: 30
    local-maximum-size: 100000

server:
  port: 10190
